package org.rhasspy.mobile.logic.settings.option

import dev.icerock.moko.resources.FileResource
import dev.icerock.moko.resources.StringResource
import org.rhasspy.mobile.MR

enum class PorcupineKeywordOption(
    override val text: StringResource,
    val file: FileResource,
    val language: PorcupineLanguageOption
) :
    IOption<PorcupineKeywordOption> {
    ALEXA(
        MR.strings.alexa,
        MR.files.porcupine_wakeword_en_alexa_android,
        PorcupineLanguageOption.EN
    ),
    AMERICANO(
        MR.strings.americano,
        MR.files.porcupine_wakeword_en_americano_android,
        PorcupineLanguageOption.EN
    ),
    BLUEBERRY(
        MR.strings.blueberry,
        MR.files.porcupine_wakeword_en_blueberry_android,
        PorcupineLanguageOption.EN
    ),
    BUMBLEBEE(
        MR.strings.bumblebee,
        MR.files.porcupine_wakeword_en_bumblebee_android,
        PorcupineLanguageOption.EN
    ),
    COMPUTER(
        MR.strings.computer,
        MR.files.porcupine_wakeword_en_computer_android,
        PorcupineLanguageOption.EN
    ),
    GRAPEFRUIT(
        MR.strings.grapefruit,
        MR.files.porcupine_wakeword_en_grapefruit_android,
        PorcupineLanguageOption.EN
    ),
    GRASSHOPPER(
        MR.strings.grasshopper,
        MR.files.porcupine_wakeword_en_grasshopper_android,
        PorcupineLanguageOption.EN
    ),
    HEY_BARISTA(
        MR.strings.hey_barista,
        MR.files.porcupine_wakeword_en_hey_barista_android,
        PorcupineLanguageOption.EN
    ),
    HEY_GOOGLE(
        MR.strings.hey_google,
        MR.files.porcupine_wakeword_en_hey_google_android,
        PorcupineLanguageOption.EN
    ),
    HEY_SIRI(
        MR.strings.hey_siri,
        MR.files.porcupine_wakeword_en_hey_siri_android,
        PorcupineLanguageOption.EN
    ),
    JARVIS(
        MR.strings.jarvis,
        MR.files.porcupine_wakeword_en_jarvis_android,
        PorcupineLanguageOption.EN
    ),
    OK_GOOGLE(
        MR.strings.ok_google,
        MR.files.porcupine_wakeword_en_ok_google_android,
        PorcupineLanguageOption.EN
    ),
    PICO_CLOCK(
        MR.strings.pico_clock,
        MR.files.porcupine_wakeword_en_pico_clock_android,
        PorcupineLanguageOption.EN
    ),
    PICOVOICE(
        MR.strings.picovoice,
        MR.files.porcupine_wakeword_en_picovoice_android,
        PorcupineLanguageOption.EN
    ),
    PORCUPINE(
        MR.strings.porcupine,
        MR.files.porcupine_wakeword_en_porcupine_android,
        PorcupineLanguageOption.EN
    ),
    TERMINATOR(
        MR.strings.terminator,
        MR.files.porcupine_wakeword_en_terminator_android,
        PorcupineLanguageOption.EN
    ),
    ANANAS(
        MR.strings.ananas,
        MR.files.porcupine_wakeword_de_ananas_android,
        PorcupineLanguageOption.DE
    ),
    HEUSCHRECKE(
        MR.strings.heuschrecke,
        MR.files.porcupine_wakeword_de_heuschrecke_android,
        PorcupineLanguageOption.DE
    ),
    HIMBEERE(
        MR.strings.himbeere,
        MR.files.porcupine_wakeword_de_himbeere_android,
        PorcupineLanguageOption.DE
    ),
    LEGUAN(
        MR.strings.leguan,
        MR.files.porcupine_wakeword_de_leguan_android,
        PorcupineLanguageOption.DE
    ),
    STACHELSCHWEIN(
        MR.strings.stachelschwein,
        MR.files.porcupine_wakeword_de_stachelschwein_android,
        PorcupineLanguageOption.DE
    ),
    EMPAREDADO(
        MR.strings.emparedado,
        MR.files.porcupine_wakeword_es_emparedado_android,
        PorcupineLanguageOption.ES
    ),
    LEOPARDO(
        MR.strings.leopardo,
        MR.files.porcupine_wakeword_es_leopardo_android,
        PorcupineLanguageOption.ES
    ),
    MANZANA(
        MR.strings.manzana,
        MR.files.porcupine_wakeword_es_manzana_android,
        PorcupineLanguageOption.ES
    ),
    MURCIELAGO(
        MR.strings.murcielago,
        MR.files.porcupine_wakeword_es_murcielago_android,
        PorcupineLanguageOption.ES
    ),
    FRAMBOISE(
        MR.strings.framboise,
        MR.files.porcupine_wakeword_fr_framboise_android,
        PorcupineLanguageOption.FR
    ),
    MON_CHOUCHOU(
        MR.strings.monChouchou,
        MR.files.porcupine_wakeword_fr_mon_chouchou_android,
        PorcupineLanguageOption.FR
    ),
    PARAPLUIE(
        MR.strings.parapluie,
        MR.files.porcupine_wakeword_fr_parapluie_android,
        PorcupineLanguageOption.FR
    ),
    PERROQUET(
        MR.strings.perroquet,
        MR.files.porcupine_wakeword_fr_perroquet_android,
        PorcupineLanguageOption.FR
    ),
    TOURNESOL(
        MR.strings.tournesol,
        MR.files.porcupine_wakeword_fr_tournesol_android,
        PorcupineLanguageOption.FR
    ),
    CAMERIERE(
        MR.strings.cameriere,
        MR.files.porcupine_wakeword_it_cameriere_android,
        PorcupineLanguageOption.IT
    ),
    ESPRESSO(
        MR.strings.espresso,
        MR.files.porcupine_wakeword_it_espresso_android,
        PorcupineLanguageOption.IT
    ),
    PORCOSPINO(
        MR.strings.porcospino,
        MR.files.porcupine_wakeword_it_porcospino_android,
        PorcupineLanguageOption.IT
    ),
    SILENZIO_BRUNO(
        MR.strings.silencioBruno,
        MR.files.porcupine_wakeword_it_silenzio_bruno_android,
        PorcupineLanguageOption.IT
    ),
    BUSHI(
        MR.strings.bushi,
        MR.files.porcupine_wakeword_ja_bushi_android,
        PorcupineLanguageOption.JA
    ),
    NINJA(
        MR.strings.ninja,
        MR.files.porcupine_wakeword_ja_ninja_android,
        PorcupineLanguageOption.JA
    ),
    RINGO(
        MR.strings.ringo,
        MR.files.porcupine_wakeword_ja_ringo_android,
        PorcupineLanguageOption.JA
    ),
    AISEUKEULIM(
        MR.strings.aieseukeulim,
        MR.files.porcupine_wakeword_ko_aiseukeulim_android,
        PorcupineLanguageOption.KO
    ),
    BIGSEUBI(
        MR.strings.bigseubi,
        MR.files.porcupine_wakeword_ko_bigseubi_android,
        PorcupineLanguageOption.KO
    ),
    KOPPULSO(
        MR.strings.koppulso,
        MR.files.porcupine_wakeword_ko_koppulso_android,
        PorcupineLanguageOption.KO
    ),
    ABACAXI(
        MR.strings.abacaxi,
        MR.files.porcupine_wakeword_pt_abacaxi_android,
        PorcupineLanguageOption.PT
    ),
    FENOMENO(
        MR.strings.fenomeno,
        MR.files.porcupine_wakeword_pt_fenomeno_android,
        PorcupineLanguageOption.PT
    ),
    FORMIGA(
        MR.strings.formiga,
        MR.files.porcupine_wakeword_pt_formiga_android,
        PorcupineLanguageOption.PT
    ),
    PORCO_ESPINHO(
        MR.strings.porcoEspinho,
        MR.files.porcupine_wakeword_pt_porco_espinho_android,
        PorcupineLanguageOption.PT
    );

    override fun findValue(value: String): PorcupineKeywordOption {
        return PorcupineKeywordOption.valueOf(value)
    }
}
/*
EN(MR.strings.english, MR.files.porcupine_params),
    DE(MR.strings.german, MR.files.porcupine_params_de),
    ES(MR.strings.spanish, MR.files.porcupine_params_es),
    FR(MR.strings.french, MR.files.porcupine_params_fr),
    IT(MR.strings.italian, MR.files.porcupine_params_it),
    JA(MR.strings.japanese, MR.files.porcupine_params_ja),
    KO(MR.strings.korean, MR.files.porcupine_params_ko),
    PT(MR.strings.portuguese, MR.files.porcupine_params_pt);

    porcupine_wakeword_es_murciélago_android
 */