name: Build CI

on:
  workflow_call:
    inputs:
      BUILD_TYPE:
        required: true
        type: string
      BUILD_TYPE_LOWERCASE:
        required: true
        type: string
    secrets:
      SIGNING_KEY:
        required: true
      ALIAS:
        required: true
      KEY_STORE_PASSWORD:
        required: true
      KEY_PASSWORD:
        required: true

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Set Up JDK 19
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '19'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      # necessary for linux/macos but doesn't work on windows
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      # run project build
      - name: Project APK Build
        run: ./gradlew androidApp:assemble${{ inputs.BUILD_TYPE }}
      # run project build
      - name: Project Bundle Build
        run: ./gradlew androidApp:bundle${{ inputs.BUILD_TYPE }}
      # sign the generated apks
      - uses: r0adkll/sign-android-release@v1
        name: Sign App APK
        id: sign_app_apk
        with:
          releaseDirectory: androidApp/build/outputs/apk/${{ inputs.BUILD_TYPE_LOWERCASE }}
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"
      # sign the generated apks
      - uses: r0adkll/sign-android-release@v1
        name: Sign App Bundle
        id: sign_app_bundle
        with:
          releaseDirectory: androidApp/build/outputs/bundle/${{ inputs.BUILD_TYPE_LOWERCASE }}
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"
      # upload apks to action
      - uses: actions/upload-artifact@v3
        with:
          name: rhasspy_mobile_aab
          path: androidApp/build/outputs/bundle/${{ inputs.BUILD_TYPE_LOWERCASE }}/androidApp-${{ inputs.BUILD_TYPE_LOWERCASE }}.aab
      # upload apks to action
      - uses: actions/upload-artifact@v3
        with:
          name: rhasspy_mobile_arm64-v8a
          path: androidApp/build/outputs/apk/${{ inputs.BUILD_TYPE_LOWERCASE }}/rhasspy_mobile_*-arm64-v8a-signed.apk
      # upload apks to action
      - uses: actions/upload-artifact@v3
        with:
          name: rhasspy_mobile_armeabi-v7a
          path: androidApp/build/outputs/apk/${{ inputs.BUILD_TYPE_LOWERCASE }}/rhasspy_mobile_*-armeabi-v7a-signed.apk
      # upload apks to action
      - uses: actions/upload-artifact@v3
        with:
          name: rhasspy_mobile_x86
          path: androidApp/build/outputs/apk/${{ inputs.BUILD_TYPE_LOWERCASE }}/rhasspy_mobile_*-x86-signed.apk
      # upload apks to action
      - uses: actions/upload-artifact@v3
        with:
          name: rhasspy_mobile_x86_64
          path: androidApp/build/outputs/apk/${{ inputs.BUILD_TYPE_LOWERCASE }}/rhasspy_mobile_*-x86_64-signed.apk


