name: Debug CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  setup:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 18.0.1+10
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18.0.1+10'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
  lint:
    needs: setup
    runs-on: windows-latest
    steps:
      - name: Android Lint Check
        run: ./gradlew lintDebug
  test:
    needs: lint
    runs-on: windows-latest
    steps:
      - name: Unit Tests
        run: ./gradlew check
  build:
    needs: test
    runs-on: windows-latest
    steps:
      - name: Project Build
        run: ./gradlew build