name: Debug Build CI

on:
  push:
    branches:
      - develop
  pull_request:
    types: [ closed ]
    branches:
      - develop

jobs:
  #build dev build
  build:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/build-ci.yml
    with:
      BUILD_TYPE: Debug
      BUILD_TYPE_LOWERCASE: debug
    secrets:
      SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
      ALIAS: ${{ secrets.ALIAS }}
      KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
  #upload dev build
  upload:
    runs-on: self-hosted
    needs: build
    steps:
      - uses: softprops/action-gh-release@v1
        with:
          name: nightly
          tag_name: nightly
          files: |
            androidApp/build/outputs/bundle/debug/androidApp-debug.aab
            androidApp/build/outputs/apk/debug/rhasspy_mobile_*-arm64-v8a-signed.apk
            androidApp/build/outputs/apk/debug/rhasspy_mobile_*-armeabi-v7a-signed.apk
            androidApp/build/outputs/apk/debug/rhasspy_mobile_*-x86-signed.apk
            androidApp/build/outputs/apk/debug/rhasspy_mobile_*-x86_64-signed.apk
