name: Debug CI

on:
  pull_request:
    branches: [ "develop" ]
    types:
      - labeled

jobs:
  build:
    runs-on: self-hosted
    if: ${{ github.event.label.name == 'automerge' }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Set Up JDK 18
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '18'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      # necessary for linux/macos but doesn't work on windows
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      # code version is increased before build
      - name: Increase Code Version
        run: ./gradlew increaseCodeVersion
      # commit new version
      - name: Commit changes
        run: |
          git config --local user.name github-actions[bot]
          git config --local user.email github-actions[bot]@users.noreply.github.com
          git commit -m "Automatically increased Version.code" -a
      #push changes
      - name: Push changes # push the output folder to your repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}
          force_with_lease: true
      # run project build
      - name: Project Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew androidApp:build sonarqube
      # sign the generated apks
      - uses: r0adkll/sign-android-release@v1
        name: Sign App APK
        id: sign_app
        with:
          releaseDirectory: androidApp/build/outputs/apk/debug
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "30.0.2"
      # upload apks to action
      - uses: actions/upload-artifact@v3
        with:
          name: Upload Artifact of signed apks
          path: androidApp/build/outputs/apk/debug/rhasspy_mobile_*.apk
      # auto approve pr
      - name: Approve Pull Request
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          method: merge
          number: ${{ github.event.pull_request.number }}
