name: Debug Build CI

on:
  push:
    branches:
      - develop

jobs:
  #build dev build
  build:
    uses: ./.github/workflows/build-ci.yml
    with:
      BUILD_TYPE: Debug
      BUILD_TYPE_LOWERCASE: debug
    secrets:
      SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
      ALIAS: ${{ secrets.ALIAS }}
      KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
  #upload dev build
  upload:
    runs-on: self-hosted
    needs: build
    uses: eine/tip@master
    with:
    tag: nightly
    rm: true
    token: ${{ secrets.GITHUB_TOKEN }}
    files: |
      androidApp/build/outputs/bundle/debug/androidApp-debug.aab
      androidApp/build/outputs/apk/debug/rhasspy_mobile_*-arm64-v8a-signed.apk
      androidApp/build/outputs/apk/debug/rhasspy_mobile_*-armeabi-v7a-signed.apk
      androidApp/build/outputs/apk/debug/rhasspy_mobile_*-x86-signed.apk
      androidApp/build/outputs/apk/debug/rhasspy_mobile_*-x86_64-signed.apk
