name: Debug CI

on:
  pull_request:
    branches: [ "debug" ]
    types:
      - labeled

jobs:
  merge:
    if: ${{ github.event.label.name == 'automerge' }}
    uses: ./.github/workflows/merge-ci.yml
    with:
      BUILD_TYPE: Release
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
      ALIAS: ${{ secrets.ALIAS }}
      KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}