name: Develop CI

on:
  pull_request:
    branches: [ "debug" ]
    types:
      - labeled

jobs:
  merge:
    if: ${{ github.event.label.name == 'automerge' }}
    uses: Nailik/rhasspy_mobile/.github/workflows/merge-ci.yml
    with:
      buildType: Debug