name: Debug CI

on:
  pull_request:
    branches: [ "develop" ]
    types:
      - labeled

jobs:
  check:
    uses: Nailik/rhasspy_mobile/.github/workflows/pullrequest-ci.yml
    with:
      buildType: Debug