name: Develop CI

on:
  pull_request:
    branches:
      - develop
    types: [ opened, labeled, synchronize ]

jobs:
  check:
    if: (contains(github.event.pull_request.labels.*.name, 'automerge') == false)
    uses: ./.github/workflows/pullrequest-ci.yml
    with:
      BUILD_TYPE: Debug
      BUILD_TYPE_LOWERCASE: debug
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_KEY: ${{ secrets.SONAR_KEY }}
  merge:
    if: contains(github.event.pull_request.labels.*.name, 'automerge')
    uses: ./.github/workflows/merge-ci.yml
    with:
      BUILD_TYPE: Debug
      BUILD_TYPE_LOWERCASE: debug
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_KEY: ${{ secrets.SONAR_KEY }}
      SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
      ALIAS: ${{ secrets.ALIAS }}
      KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
  approve:
    needs: merge
    runs-on: self-hosted
    steps:
      # auto approve pr
      - name: Approve Pull Request
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          method: merge
          number: ${{ github.event.pull_request.number }}
