name: Develop CI

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  check:
    uses: ./.github/workflows/pullrequest-ci.yml
    with:
      BUILD_TYPE: Release
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}