name: Debug CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 18.0.1+10
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18.0.1+10'
          cache: gradle
        # Removed chmod for windows
      #- name: Grant execute permission for gradlew
      #  run: chmod +x gradlew
      - name: Android Lint Check
        run: ./gradlew lintDebug
      - name: Unit Tests
        run: ./gradlew testDebugUnitTest
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Project Build
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew build sonarqube
      - name: Build Debug APK
        run: ./gradlew assembleDebug

