name: Develop CI

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  check:
    runs-on: self-hosted
    steps:
      - uses: ./.github/workflows/pullrequest-ci.yml
        with:
          BUILD_TYPE: Release
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}