name: Develop CI

on:
  pull_request:
    branches:
      - develop
    types: [labeled, edited, synchronize]

jobs:
  check:
    if: (contains(github.event.pull_request.labels.*.name, 'automerge') == false)
    uses: ./.github/workflows/pullrequest-ci.yml
    with:
      BUILD_TYPE: Debug
      BUILD_TYPE_LOWERCASE: debug
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  merge:
    if: contains(github.event.pull_request.labels.*.name, 'automerge')
    uses: ./.github/workflows/merge-ci.yml
    with:
      BUILD_TYPE: Debug
      BUILD_TYPE_LOWERCASE: debug
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
      ALIAS: ${{ secrets.ALIAS }}
      KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}