name: Master CI

on:
  pull_request:
    branches:
      - master
    types: [labeled, edited, synchronize]

jobs:
  check:
    uses: ./.github/workflows/pullrequest-ci.yml
    with:
      BUILD_TYPE: Debug
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  merge:
    needs: check
    if: ${{ github.event.label.name == 'automerge' }}
    uses: ./.github/workflows/merge-ci.yml
    with:
      BUILD_TYPE: Release
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
      ALIAS: ${{ secrets.ALIAS }}
      KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
  release:
    runs-on: self-hosted
    needs: merge
    steps:
      #download artifacts from build
      - uses: actions/download-artifact@master
        with:
          name: CompiledProject
          path: androidApp/build/outputs/bundle/release/
      # upload release apk
      - name: Create Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: ${{ env.version }}
          prerelease: true
          title: Release ${{ env.version }}
          files: |
            androidApp/build/outputs/bundle/release/androidApp-release.aab
            androidApp/build/outputs/apk/release/rhasspy_mobile_*-arm64-v8a-signed.apk
            androidApp/build/outputs/apk/release/rhasspy_mobile_*-armeabi-v7a-signed.apk
            androidApp/build/outputs/apk/release/rhasspy_mobile_*-x86-signed.apk
            androidApp/build/outputs/apk/release/rhasspy_mobile_*-x86_64-signed.apk
      # auto approve pr
      - name: Approve Pull Request
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          method: merge
          number: ${{ github.event.pull_request.number }}
