name: Merge CI

on:
  workflow_call:
    inputs:
      buildType:
        required: true
        type: string

jobs:
  checks:
    runs-on: self-hosted
    uses: octo-org/example-repo/.github/workflows/reusable-workflow.yml@main
    with:
      config-path: .github/labeler.yml
    secrets:
      buildType: ${{ inputs.buildType }}
  uiTest:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Set Up JDK 18
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '18'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      # necessary for linux/macos but doesn't work on windows
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      # android UI Test
      - name: Android UI Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: default
          arch: arm64-v8a
          profile: Nexus 6
          script: ./gradlew androidApp:connectedCheck
       # better looking test report inside github
      - name: Create Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Test Report
          path: |
            androidApp/build/outputs/androidTest-results/connected/TEST-*.xml
            MultiPlatformLibrary/build/test-results/test*UnitTest/TEST-*.xml
          reporter: java-junit
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Set Up JDK 18
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '18'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      # necessary for linux/macos but doesn't work on windows
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      # run project build
      - name: Project APK Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./gradlew androidApp:build{{ inputs.buildType }}
          ./gradlew androidApp:assemble{{ inputs.buildType }}
      # sign the generated apks
      - uses: r0adkll/sign-android-release@v1
        name: Sign App APK
        id: sign_app
        with:
          releaseDirectory: androidApp/build/outputs/apk/${{ inputs.buildType }}
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "33.0.1"
      # sign the generated apks
      - uses: r0adkll/sign-android-release@v1
        name: Sign App Bundle
        id: sign_app
        with:
          releaseDirectory: androidApp/build/outputs/bundle/${{ inputs.buildType }}
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "33.0.1"
      # upload apks to action
      - uses: actions/upload-artifact@v3
        with:
          name: Upload Artifact of signed apks
          path: |
            androidApp/build/outputs/bundle/${{ inputs.buildType }}/androidApp-release.aab
            androidApp/build/outputs/apk/${{ inputs.buildType }}/rhasspy_mobile_*-arm64-v8a-signed.apk
            androidApp/build/outputs/apk/${{ inputs.buildType }}/rhasspy_mobile_*-armeabi-v7a-signed.apk
            androidApp/build/outputs/apk/${{ inputs.buildType }}/rhasspy_mobile_*-x86-signed.apk
            androidApp/build/outputs/apk/${{ inputs.buildType }}/rhasspy_mobile_*-x86_64-signed.apk


